//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario_Pasaje_Inteligentee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Empresa
    {
        public int EmpresaID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public string Departamento { get; set; }
        public string Pais { get; set; }
        public Nullable<System.DateTime> Fec_cre { get; set; }
        public Nullable<System.DateTime> Fec_mod { get; set; }
    }
}
